baseURL = "//datasketch.github.io/agacolombia"
title = "Sitio"
theme = "hugo-titi"
disqusShortname = "datasketch"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

publishDir="docs"

[blackfriday]
  hrefTargetBlank = true


#Parametros de configuración
[params]
  [params.fonts]
  body = "Arimoblog"
  headings = "Didact Gothic"
  #Footer
  [params.footer]
    text = "Comité de la **Alianza para el Gobierno Abierto** en Colombia:"
    # footer background color
    bg = "white"
    # footer text color
    color = "black"
    
  [params.nav]
  bg = "#303030"
  color = "white"
  logo = "/images/logoaga.jpg"
  logowidth = "150px"
  fixed = false
  [[params.social]]
  icon = "twitter"
  url = "https://twitter.com/"
  [[params.social]]
  icon = "facebook"
  url = "https://facebook.com/"
    
    [[params.social]]
    icon = "instagram"
    url = "https://instagram.com/"
    
#Barra de navegación
[menu]
    
    [[menu.nav]]
    name = "Inicio"
    url = "http://agacolombia.org/"
    weight = 1
    
    [[menu.burger]]
    nname = "Inicio"
    url = "http://agacolombia.org/"
    

