baseURL = "/"
title = "Sitio"
theme = "hugo-titi"
disqusShortname = "datasketch"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[blackfriday]
  hrefTargetBlank = true


#Parametros de configuraci贸n
[params]
  #Footer
  [params.footer]
    text = "Fabuloso Footer. [Datasketch](https://www.datasketch.co)"
    # footer background color
    bg = "black"
    # footer text color
    color = "white"
  [params.nav]
  bg = "#303030"
  color = "white"
  logo = "/images/logoaga.jpg"
  logowidth = "150px"
  fixed = false
  [[params.social]]
  icon = "twitter"
  url = "https://twitter.com/datasketch"
  [[params.social]]
  icon = "facebook"
  url = "https://facebook.com/datasketch"
    
    [[params.social]]
    icon = "instagram"
    url = "https://instagram.com/datasketch"
    
#Barra de navegaci贸n
[menu]
    
    [[menu.nav]]
    name = "Inicio"
    url = "http://agacolombia.org/"
    weight = 1
    
    [[menu.nav]]
    name = "Misi贸n y objetivos"
    url = "http://agacolombia.org/mision"
    weight = 2
    
     [[menu.nav]]
    name = "Blog"
    url = "http://agacolombia.org/blog"
    weight = 3
    
    [[menu.nav]]
    name = "AGA en territorio"
    url = "http://agacolombia.org/aga-en-territorio"
    weight = 4
    
    [[menu.nav]]
    name = "Preguntas frecuentes"
    url = "http://agacolombia.org/preguntas-frecuentes"
    weight = 5
    
    [[menu.burger]]
    nname = "Inicio"
    url = "http://agacolombia.org/"
    
      [[menu.burger]]
    name = "Misi贸n y objetivos"
    url = "http://agacolombia.org/mision"
    
    [[menu.burger]]
    name = "Blog"
    url = "http://agacolombia.org/blog"
    
    [[menu.burger]]
    name = "AGA en territorio"
    url = "http://agacolombia.org/aga-en-territorio"
    
    [[menu.burger]]
    name = "Preguntas frecuentes"
    url = "http://agacolombia.org/preguntas-frecuentes"